// 큐레이션된 글감 풀. 시드 스크립트가 날짜 순서대로 배정한다.
// 글감은 서버(관리자)만 생성하므로 이 파일은 앱 번들에 포함되지 않는다.

const PROMPT_POOL = [
  // 관계
  { title: '우정', category: '관계' },
  { title: '가족', category: '관계' },
  { title: '첫사랑', category: '관계' },
  { title: '이별', category: '관계' },
  { title: '오래된 친구', category: '관계' },
  { title: '엄마', category: '관계' },
  { title: '아빠', category: '관계' },
  { title: '형제', category: '관계' },
  { title: '스승', category: '관계' },
  { title: '동료', category: '관계' },
  { title: '이웃', category: '관계' },
  { title: '반려동물', category: '관계' },
  { title: '짝사랑', category: '관계' },
  { title: '재회', category: '관계' },
  { title: '거리감', category: '관계' },
  { title: '신뢰', category: '관계' },
  { title: '배신', category: '관계' },
  { title: '화해', category: '관계' },
  { title: '연락', category: '관계' },
  { title: '작별', category: '관계' },

  // 감정
  { title: '행복', category: '감정' },
  { title: '후회', category: '감정' },
  { title: '설렘', category: '감정' },
  { title: '외로움', category: '감정' },
  { title: '분노', category: '감정' },
  { title: '평온', category: '감정' },
  { title: '불안', category: '감정' },
  { title: '기대', category: '감정' },
  { title: '질투', category: '감정' },
  { title: '고마움', category: '감정' },
  { title: '미안함', category: '감정' },
  { title: '서러움', category: '감정' },
  { title: '뿌듯함', category: '감정' },
  { title: '허무', category: '감정' },
  { title: '위로', category: '감정' },
  { title: '두려움', category: '감정' },
  { title: '안도', category: '감정' },
  { title: '그리움', category: '감정' },
  { title: '벅차오름', category: '감정' },
  { title: '무덤덤함', category: '감정' },

  // 자아
  { title: '꿈', category: '자아' },
  { title: '성공', category: '자아' },
  { title: '실패', category: '자아' },
  { title: '재능', category: '자아' },
  { title: '노력', category: '자아' },
  { title: '한계', category: '자아' },
  { title: '변화', category: '자아' },
  { title: '습관', category: '자아' },
  { title: '자존감', category: '자아' },
  { title: '열등감', category: '자아' },
  { title: '성장', category: '자아' },
  { title: '고집', category: '자아' },
  { title: '나다움', category: '자아' },
  { title: '약점', category: '자아' },
  { title: '강점', category: '자아' },
  { title: '게으름', category: '자아' },
  { title: '집중', category: '자아' },
  { title: '포기', category: '자아' },
  { title: '끈기', category: '자아' },
  { title: '이름', category: '자아' },

  // 가치
  { title: '자유', category: '가치' },
  { title: '용기', category: '가치' },
  { title: '정직', category: '가치' },
  { title: '책임', category: '가치' },
  { title: '배려', category: '가치' },
  { title: '공정', category: '가치' },
  { title: '겸허', category: '가치' },
  { title: '인내심', category: '가치' },
  { title: '희망', category: '가치' },
  { title: '진심', category: '가치' },
  { title: '약속', category: '가치' },
  { title: '존중', category: '가치' },
  { title: '용서', category: '가치' },
  { title: '나눔', category: '가치' },
  { title: '정의', category: '가치' },

  // 시간
  { title: '어제', category: '시간' },
  { title: '오늘', category: '시간' },
  { title: '내일', category: '시간' },
  { title: '새벽', category: '시간' },
  { title: '아침', category: '시간' },
  { title: '저녁', category: '시간' },
  { title: '밤', category: '시간' },
  { title: '주말', category: '시간' },
  { title: '기다림', category: '시간' },
  { title: '순간', category: '시간' },
  { title: '반복', category: '시간' },
  { title: '처음', category: '시간' },
  { title: '마지막', category: '시간' },
  { title: '스무 살', category: '시간' },
  { title: '어린 시절', category: '시간' },

  // 계절/자연
  { title: '봄', category: '계절' },
  { title: '여름', category: '계절' },
  { title: '가을', category: '계절' },
  { title: '겨울', category: '계절' },
  { title: '비', category: '계절' },
  { title: '눈', category: '계절' },
  { title: '바람', category: '계절' },
  { title: '햇살', category: '계절' },
  { title: '바다', category: '계절' },
  { title: '산', category: '계절' },
  { title: '하늘', category: '계절' },
  { title: '별', category: '계절' },
  { title: '달', category: '계절' },
  { title: '나무', category: '계절' },
  { title: '꽃', category: '계절' },
  { title: '장마', category: '계절' },
  { title: '첫눈', category: '계절' },
  { title: '노을', category: '계절' },
  { title: '안개', category: '계절' },
  { title: '새벽 공기', category: '계절' },

  // 일상
  { title: '집', category: '일상' },
  { title: '방', category: '일상' },
  { title: '길', category: '일상' },
  { title: '음악', category: '일상' },
  { title: '책', category: '일상' },
  { title: '영화', category: '일상' },
  { title: '커피', category: '일상' },
  { title: '밥', category: '일상' },
  { title: '잠', category: '일상' },
  { title: '산책', category: '일상' },
  { title: '지하철', category: '일상' },
  { title: '창밖', category: '일상' },
  { title: '편지', category: '일상' },
  { title: '사진', category: '일상' },
  { title: '옷', category: '일상' },
  { title: '여행', category: '일상' },
  { title: '휴식', category: '일상' },
  { title: '청소', category: '일상' },
  { title: '요리', category: '일상' },
  { title: '운동', category: '일상' },
  { title: '전화', category: '일상' },
  { title: '메모', category: '일상' },
  { title: '우산', category: '일상' },
  { title: '가방', category: '일상' },
  { title: '거울', category: '일상' },

  // 상황형
  { title: '10년 후의 나', category: '상황' },
  { title: '다시 돌아가고 싶은 순간', category: '상황' },
  { title: '가장 기억에 남는 하루', category: '상황' },
  { title: '처음 만난 사람', category: '상황' },
  { title: '잊고 싶은 기억', category: '상황' },
  { title: '내가 가장 고마웠던 사람', category: '상황' },
  { title: '가장 크게 웃었던 날', category: '상황' },
  { title: '혼자였던 밤', category: '상황' },
  { title: '처음 실패했던 날', category: '상황' },
  { title: '누군가에게 받은 위로', category: '상황' },
  { title: '아무것도 하지 않은 하루', category: '상황' },
  { title: '오래 준비했던 일', category: '상황' },
  { title: '예상하지 못한 행운', category: '상황' },
  { title: '끝까지 해낸 일', category: '상황' },
  { title: '미루고 있는 일', category: '상황' },
  { title: '말하지 못한 마음', category: '상황' },
  { title: '이제는 웃으며 말할 수 있는 일', category: '상황' },
  { title: '아직 부끄러운 기억', category: '상황' },
  { title: '누군가를 처음 좋아했던 날', category: '상황' },
  { title: '내 인생의 전환점', category: '상황' },
  { title: '가장 오래 걸린 결정', category: '상황' },
  { title: '지금 가장 소중한 것', category: '상황' },
  { title: '어른이 되었다고 느낀 순간', category: '상황' },
  { title: '작은 것에 감동한 날', category: '상황' },
  { title: '다 내려놓고 싶었던 날', category: '상황' },
  { title: '몰래 울었던 날', category: '상황' },
  { title: '누구에게도 말하지 않은 계획', category: '상황' },
  { title: '내 편이 되어준 사람', category: '상황' },
  { title: '한 번 더 하고 싶은 일', category: '상황' },
  { title: '다시는 하고 싶지 않은 일', category: '상황' },

  // 질문형
  { title: '행복이란 무엇일까?', category: '질문' },
  { title: '친구란 무엇일까?', category: '질문' },
  { title: '성공했다고 느끼는 순간은 언제일까?', category: '질문' },
  { title: '어른이란 무엇일까?', category: '질문' },
  { title: '사랑은 무엇으로 알아볼까?', category: '질문' },
  { title: '용기는 어디서 나올까?', category: '질문' },
  { title: '왜 우리는 후회할까?', category: '질문' },
  { title: '좋은 사람이란 어떤 사람일까?', category: '질문' },
  { title: '나는 무엇을 두려워할까?', category: '질문' },
  { title: '쉬는 건 왜 어려울까?', category: '질문' },
  { title: '기억은 왜 변할까?', category: '질문' },
  { title: '외로움은 나쁜 걸까?', category: '질문' },
  { title: '무엇을 위해 참을 수 있을까?', category: '질문' },
  { title: '지금의 나에게 필요한 말은?', category: '질문' },
  { title: '무엇을 남기고 싶을까?', category: '질문' },
  { title: '왜 어떤 말은 오래 남을까?', category: '질문' },
  { title: '내가 바꿀 수 있는 것은 무엇일까?', category: '질문' },
  { title: '충분하다는 건 어떤 느낌일까?', category: '질문' },
  { title: '왜 누군가는 잊히지 않을까?', category: '질문' },
  { title: '나는 언제 가장 나다울까?', category: '질문' },

  // 관계 확장
  { title: '같이 밥 먹고 싶은 사람', category: '관계' },
  { title: '닮고 싶은 사람', category: '관계' },
  { title: '미워했던 사람', category: '관계' },
  { title: '이해하게 된 사람', category: '관계' },
  { title: '나를 잘 아는 사람', category: '관계' },
  { title: '오래 기억될 한마디', category: '관계' },
  { title: '함께 걸었던 길', category: '관계' },
  { title: '연락하지 않는 사이', category: '관계' },
  { title: '고백', category: '관계' },
  { title: '기대고 싶은 어깨', category: '관계' },

  // 감정 확장
  { title: '괜찮다는 말', category: '감정' },
  { title: '울고 싶은 날', category: '감정' },
  { title: '아무 이유 없는 기분', category: '감정' },
  { title: '조용한 기쁨', category: '감정' },
  { title: '버티는 마음', category: '감정' },
  { title: '지친 마음', category: '감정' },
  { title: '설명할 수 없는 슬픔', category: '감정' },
  { title: '마음이 놓이는 순간', category: '감정' },
  { title: '작은 용기', category: '감정' },
  { title: '뜻밖의 감동', category: '감정' },

  // 자아 확장
  { title: '내가 잘하는 일', category: '자아' },
  { title: '내가 못하는 일', category: '자아' },
  { title: '고치고 싶은 점', category: '자아' },
  { title: '지키고 싶은 것', category: '자아' },
  { title: '나만의 규칙', category: '자아' },
  { title: '혼자 있는 시간', category: '자아' },
  { title: '나를 움직이는 것', category: '자아' },
  { title: '멈추고 싶은 순간', category: '자아' },
  { title: '나에게 하는 거짓말', category: '자아' },
  { title: '결국 남는 것', category: '자아' },

  // 일상 확장
  { title: '자주 듣는 노래', category: '일상' },
  { title: '오래 쓰는 물건', category: '일상' },
  { title: '좋아하는 냄새', category: '일상' },
  { title: '가장 편한 자리', category: '일상' },
  { title: '주머니 속', category: '일상' },
  { title: '늘 지나치는 풍경', category: '일상' },
  { title: '오늘 먹은 것', category: '일상' },
  { title: '작은 사치', category: '일상' },
  { title: '버리지 못한 것', category: '일상' },
  { title: '새로 사고 싶은 것', category: '일상' },
  { title: '오래된 습관', category: '일상' },
  { title: '집에 오는 길', category: '일상' },
  { title: '문득 떠오른 생각', category: '일상' },
  { title: '오늘의 날씨', category: '일상' },
  { title: '내 하루의 시작', category: '일상' },
];

module.exports = { PROMPT_POOL };
